# Prompt -> LLM -> SQL Query : DONE
# SQL Query -> DB -> Records : DONE
# First we will try it on Simple DB Like SQLite3 DB then we can Scale up to Like SQL-Server DB
# Try with more than 1 Table with Relationship between them. : DONE
# Display the Schema : DONE

import streamlit as st
import pandas as pd
from dotenv import load_dotenv
import os
import sqlite3
from google import genai

# Load all Environemnt Variables(.env File)
load_dotenv()

# Setup Gemini API Key
api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    st.error("❌ GEMINI_API_KEY is missing! Please check your .env file or environment variables.")
else:
    client = genai.Client()

# Load Gemini Model and Provide SQL Query as a Response
def get_gemini_response(question: str, prompt: str) -> str:
    """Generates an SQL query from a natural language question using Gemini.

    This function utilizes the Google GenAI SDK (Gemini 2.5 Flash) to translate
    a human-written question into a structured, executable SQL query based on 
    the system instructions provided in the prompt.

    Args:
        question (str): The natural language query or question asked by the user.
        prompt (str): The system prompt containing database schema details and guidelines.

    Returns:
        str: The raw, cleaned SQL query generated by the model.
    """
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[prompt, question],
    )
    return response.text.strip()

# Take this SQL Query to get records from DB
def get_records(SQL_Query: str, db: str) -> list:
    """Executes a given SQL query against a local SQLite database and fetches results.

    Connects to the specified SQLite database file, creates a cursor, executes the
    provided query, commits changes (if any), and safely closes the connection.

    Args:
        SQL_Query (str): The executable SQL string generated by the LLM.
        db (str): The file path to the local SQLite database (e.g., 'Faculty.db').

    Returns:
        list: A list of tuples containing the raw rows fetched from the database.
        Returns an empty list if no records match.
    """
    conn = sqlite3.connect(db)
    cursor = conn.cursor()
    cursor.execute(SQL_Query)
    data = cursor.fetchall()
    
    conn.commit()
    conn.close()

    return data


# Define the Prompt
prompt = " ".join([
    "You are an Expert in Converting Questions into SQL Query\n",
    "The database has TWO tables with a relationship:\n",
    "1. Students(Id, Name, Class)\n",
    "2. Marks(MarkId, StudentId, Subject, Score) -> StudentId links to Students(Id)\n\n",
    "Guidelines: \n",
    "- Provide ONLY the executable SQL query. Do NOT wrap it in ```sql ... ``` or markdown tags.\n",
    "- Do NOT include any explanations or extra text.\n\n",
    "- Use SQL JOIN when the question requires data from both tables.\n\n",
    "Example1: How many entries are present in the table?\n",
    "SQL Query: SELECT COUNT(*) FROM Students;\n\n",
    "Example2: Tell me about Students who studying Data Science\n",
    "SQL Query: SELECT * FROM Students WHERE Class = 'Data Science';\n\n",
    "Example3: Give me the marks of Ahmed Akram in Data Science\n",
    "SQL Query: SELECT Marks.Subject, Marks.Score FROM Marks JOIN Students ON Marks.StudentId = Students.Id WHERE Students.Name = 'Ahmed Akram';\n\n",
    "Question: "
])

# ---------------------------------------------------------------------------------------
# Streamlit Front-End App
st.set_page_config(page_title="Talk with the Database", page_icon="🗄️", layout="wide")
# st.header("🗄️ Talk with the Database (Text-to-SQL)")
st.markdown(
    """
    <div style="background-color:#1E293B; padding:20px; border-radius:10px; margin-bottom:25px">
        <h1 style="color:#F8FAFC; text-align:center; margin:0;">🗄️ Text-to-SQL AI Engine</h1>
        <p style="color:#94A3B8; text-align:center; margin:5px 0 0 0;">Talk directly with your Faculty Database using natural language powered by Gemini 2.5</p>
    </div>
""",
    unsafe_allow_html=True,
)

with st.sidebar:
    st.header("🗺️ Database Schema Visualizer")
    st.info(
        "This app connects to `Faculty.db` which contains two related tables:"
    )
    with st.expander("👤 Table: Students"):
        st.markdown(
            """
        - **Id** (INTEGER, PK)
        - **Name** (VARCHAR)
        - **DoB** (TEXT)
        - **Section** (INTEGER)
        """
        )
    
    with st.expander("📊 Table: Marks"):
        st.markdown(
            """
        - **MarkId** (INTEGER, PK)
        - **StudentId** (INTEGER, FK)
        - **Subject** (VARCHAR)
        - **Score** (INTEGER)
        """
        )
    
    st.caption("The Triple AI - Powered by Poetry • Google GenAI • Streamlit")

st.subheader("💡 Ask your Question")

question = st.text_input(
    "Enter your query in plain English or Arabic:",
    placeholder="e.g., Show me the marks of Ahmed Akram in Machine Learning or list students in Section 2.",
    key="input",
)

submit = st.button("🚀 Generate SQL & Run Query", type="primary")

# If Submit is Clicked
if submit:
    if question.strip() == "":
        st.warning("⚠️Please enter a question first!")
    else:
        with st.spinner("🤖 Gemini is analyzing the schema and drafting SQL..."):
            try:
                generated_sql = get_gemini_response(question, prompt)
                tab_results, tab_code = st.tabs(
                    ["📊 Database Records", "💻 Generated SQL Code"]
                )
                
                with tab_results:
                    data = get_records(generated_sql, "Faculty.db")
                    if not data:
                        st.info("ℹ️ Query executed successfully, but no records were found.")
                    else:
                        st.success(f"🎉 Successfully fetched {len(data)} rows!")
                        df = pd.DataFrame(data)
                        st.dataframe(df, width='stretch')
                
                with tab_code:
                    st.markdown(
                        "The AI generated the following optimized SQL script:"
                    )
                    st.code(generated_sql, language='sql')

            except Exception as e:
                st.error(f"❌An Error Occurred: {e}!")