from src.config import client

# Load Gemini Model and Provide SQL Query as a Response
# Apply Role-Based Access Control (RBAC)
def get_gemini_response(question: str, role: str) -> str:
    """Generates an SQL query from a natural language question using Gemini.
        OR Block Access based on User's Role (RBAC).
    
    This function utilizes the Google GenAI SDK (Gemini 2.5 Flash) to translate
    a human-written question into a structured, executable SQL query based on 
    the system instructions provided in the prompt.

    Args:
        question (str): The natural language query or question asked by the user.
        
    Returns:
        str: The raw, cleaned SQL query generated by the model.
    """
    if role.lower() == "user":
        role_guardrail = (
            "- CRITICAL SECURITY GUARDRAIL: You are in READ-ONLY mode for this user.\n"
            "- You are STRICTLY FORBIDDEN from generating any data-modifying queries such as DELETE, DROP, UPDATE, INSERT, ALTER, or TRUNCATE.\n"
            "- If the user's question asks to delete, modify, change, or drop anything, respond with exactly one word: FORBIDDEN\n"
        )
    else:
        role_guardrail = "- You are in ADMIN mode. You are allowed to generate any query including INSERT, UPDATE, DELETE, and ALTER if requested.\n"
    
    # Define the Prompt -> The system prompt containing database schema details and guidelines.
    prompt = " ".join([
        "You are an Expert in Converting Questions into SQL Query\n",
        "The database has TWO tables with a relationship:\n",
        "1. Students(Id, Name, Class)\n",
        "2. Marks(MarkId, StudentId, Subject, Score) -> StudentId links to Students(Id)\n\n",
        "Guidelines: \n",
        role_guardrail,
        "- Provide ONLY the executable SQL query. Do NOT wrap it in ```sql ... ``` or markdown tags.\n",
        "- Do NOT include any explanations or extra text.\n\n",
        "- Use SQL JOIN when the question requires data from both tables.\n\n",
        "Example1: How many entries are present in the table?\n",
        "SQL Query: SELECT COUNT(*) FROM Students;\n\n",
        "Example2: Tell me about Students who studying Data Science\n",
        "SQL Query: SELECT * FROM Students WHERE Class = 'Data Science';\n\n",
        "Example3: Give me the marks of Ahmed Akram in Data Science\n",
        "SQL Query: SELECT Marks.Subject, Marks.Score FROM Marks JOIN Students ON Marks.StudentId = Students.Id WHERE Students.Name = 'Ahmed Akram';\n\n",
        "Question: "
    ])
    
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=[prompt, question],
    )
    return response.text.strip()
