from src.config import DB_PATH
import sqlite3
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB_PATH = os.path.join(BASE_DIR, "Faculty.db")

# Take this SQL Query to get records from DB
def get_records(SQL_Query: str) -> list:
    """Executes a given SQL query against a local SQLite database and fetches results.

    Connects to the specified SQLite database file, creates a cursor, executes the
    provided query, commits changes (if any), and safely closes the connection.

    Args:
        SQL_Query (str): The executable SQL string generated by the LLM.
        db (str): The file path to the local SQLite database (e.g., 'Faculty.db').

    Returns:
        list: A list of tuples containing the raw rows fetched from the database.
        Returns an empty list if no records match.
    """
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    cursor.execute(SQL_Query)
    data = cursor.fetchall()
    
    conn.commit()
    conn.close()

    return data
